name: Build and Test Electron App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Test (optional)
        run: npm test

      - name: Publish artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: electron-app
          path: dist